version: "3"

services:
  client:
    build:
        context: ./client
        dockerfile: Dockerfile
    image: client
    container_name: node_client
    restart: unless-stopped
    environment:
      LOGLEVEL: "info"
    ports:
     - "3000:3000"
    networks:
      - micro
    depends_on:
     - redis

  # worker:
  #   build: ./worker
  #   container_name: node_worker
  #   restart: unless-stopped
  #   environment:
  #     LOGLEVEL: "info"
  #   depends_on:
  #    - redis

  monitor:
    build:
      context: ./monitor
      dockerfile: Dockerfile
    image: monitor
    container_name: node_monitor
    restart: unless-stopped
    environment:
      LOGLEVEL: "info"
    ports:
     - "3001:4567"
    networks:
      - micro
    depends_on:
     - redis

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - micro

networks:
  micro: null
